### Get account balance
GRPC localhost:6565/sec06.BankService/GetAccountBalance
Content-Type: application/json

{
  "account_number": 5
}

### Get all accounts
GRPC localhost:6565/sec06.BankService/GetAllAccounts
Content-Type: application/stream+json

{}

### Withdraw / Deduct money
GRPC localhost:6565/sec06.BankService/Withdraw

{
  "account_number": 1,
  "amount": 50
}